baseurl = "http://new.sensualmassage.ru/"
copyright = "All rights reserved"
languagecode = "ru-RU"
paginate = 5
pluralizelisttitles = false
theme = "hugo-theme-casper"
title = "Sensual massage — Чувственный массаж"
[[menu.main]]
identifier = "blog"
name = "Блог"
url = "/"
weight = 1
[params]
author = "_"
authorbio = "Massage enthusiast."
authorlocation = "Moscow"
authorwebsite = "http://sensualmassage.ru"
cover = "images/cover.jpg"
customFooterPartial = "netlify.html"
description = "Чувственный массаж: искусство касаться, чувствовать, любить"
hideHUGOSupport = false
logo = "images/logo.png"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
